# Generated by Django 5.2.8 on 2025-11-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Üniversite', 'verbose_name_plural': 'Üniversiteler'},
        ),
    ]
